"""Generate small, copyright-free OCR samples used by the digitization smoke test."""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

SAMPLES_DIR = Path(__file__).resolve().parent
WIDTH = 1200
HEIGHT = 1600


def font(size: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates = [
        Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
        Path("/System/Library/Fonts/Supplemental/Arial.ttf"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return ImageFont.truetype(candidate, size=size)
    return ImageFont.load_default()


def page(number: int, lines: list[str]) -> Image.Image:
    image = Image.new("RGB", (WIDTH, HEIGHT), "white")
    draw = ImageDraw.Draw(image)
    draw.rectangle((80, 80, WIDTH - 80, HEIGHT - 80), outline="#203a32", width=4)
    draw.text((140, 145), "HCMUS DIGITAL LIBRARY", fill="#173d32", font=font(54))
    draw.text((140, 255), f"OCR SAMPLE - PAGE {number}", fill="#326b5a", font=font(38))
    y = 410
    for line in lines:
        draw.text((140, y), line, fill="black", font=font(34))
        y += 72
    draw.text(
        (140, HEIGHT - 190),
        "Generated by the HCMUS-LDMS sample script. No copyrighted source text.",
        fill="#425e55",
        font=font(24),
    )
    return image


def main() -> None:
    first = page(
        1,
        [
            "Library digitization turns scanned pages into searchable text.",
            "This page checks English OCR and PNG preview generation.",
            "Document code: LDMS SAMPLE 2026.",
        ],
    )
    second = page(
        2,
        [
            "Pages must remain in ascending page-number order.",
            "The publish worker packages edited text into an EPUB file.",
            "Retry is available when an OCR job fails.",
        ],
    )
    first.save(SAMPLES_DIR / "one-page.png", format="PNG", optimize=True)
    first.save(
        SAMPLES_DIR / "two-page.pdf",
        format="PDF",
        save_all=True,
        append_images=[second],
        resolution=150,
    )
    first.close()
    second.close()


if __name__ == "__main__":
    main()
